services:
  fastapi_healthcare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_healthcare
    env_file:
      - .env
    environment:
      DB_HOST: healthcare_mysql
    ports:
      - "8000:8000"
    depends_on:
      healthcare_mysql:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  healthcare_mysql:
    image: mysql:8.4
    container_name: healthcare_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - healthcare_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    restart: unless-stopped

volumes:
  healthcare_mysql_data:
