"""remove created by

Revision ID: 201d89d4de37
Revises: 6b7c21947268
Create Date: 2026-08-30 09:30:20.250809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '201d89d4de37'
down_revision: Union[str, Sequence[str], None] = '6b7c21947268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medicalrecords_ibfk_4'), 'medicalrecords', type_='foreignkey')
    op.drop_column('medicalrecords', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecords', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('medicalrecords_ibfk_4'), 'medicalrecords', 'doctors', ['created_by'], ['doctor_id'])
    # ### end Alembic commands ###
