"""initial_schema

Revision ID: 6b7c21947268
Revises: 5e92ca4f11a5
Create Date: 2026-08-29 12:38:40.667569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7c21947268'
down_revision: Union[str, Sequence[str], None] = '5e92ca4f11a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecords', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medicalrecords', 'doctors', ['created_by'], ['doctor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicalrecords', type_='foreignkey')
    op.drop_column('medicalrecords', 'created_by')
    # ### end Alembic commands ###
