"""modify patient

Revision ID: 8e798e2e9f44
Revises: 181f192290d7
Create Date: 2026-08-19 15:24:39.728112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e798e2e9f44'
down_revision: Union[str, Sequence[str], None] = '181f192290d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reasons', sa.Text(), nullable=False))
    op.add_column('appointments', sa.Column('requested_date', sa.Date(), nullable=False))
    op.add_column('doctors', sa.Column('duty', sa.Enum('OFF_DUTY', 'ACTIVE', name='duty', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'duty')
    op.drop_column('appointments', 'requested_date')
    op.drop_column('appointments', 'reasons')
    # ### end Alembic commands ###
